<?php
	include_once("DatabaseConnector.php");
	include_once("User.php");
	include_once("UserDatabase.php");
	include_once("Exam.php");
	include_once("ExamDatabase.php");
	include_once("ExamUnit.php");
	include_once("ExamUnitDatabase.php");
	include_once("Student.php");
	include_once("StudentDatabase.php");
	include_once("Record.php");
	include_once("RecordDatabase.php");
?>
